### ISSUE TITLE
🚀 [FEAT] S3 이미지 생성 후 이미지 value RDB 저장 기능 구현

### ISSUE THREAD

**Issue by voidmelody** [12-zodiac-signs-devcourse/BE-ZZAL-MYU#17]
## 🚙  구현 기능 명세
기존에는 RDB에서 S3 이미지의 key만 가지고 있었기에, 이미지 url(value)를 가져오기 위해선 s3와 계속 통신을 진행해야 했습니다.
하지만 s3의 value는 변경되지 않는 값이기에, RDB에서 이를 저장하는 방향으로 구현 합의가 이루어졌기에 구현을 진행합니다.
또한, 이미지의 key에 user의 이메일을 추가하는 방식으로 구현합니다.

## 🚌  Todo
- [x] 이미지 업로드 시 이미지 key & value rdb 저장
- [x] 이미지 key에 유저의 email을 추가
- [x] 이미지 삭제 시 해당 유저가 등록한 이미지인지 확인 로직 추가
